version: "3.9"
name: ml_entrega_2_modelos_1

services:
  ml_model:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml_model
    volumes:
      - .:/app
    working_dir: /app
    tty: true

  train:
    extends:
      service: ml_model
    command: >
      python3 train.py
      --data_file train.csv
      --model_file model.pkl
      --overwrite_model

  predict:
    extends:
      service: ml_model
    command: >
      python3 predict.py
      --input_file test.csv
      --predictions_file predictions.csv
      --model_file model.pkl
